[package]
name = "pass3d"
version = "0.1.0"
authors = ["3Dpass"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"

[dependencies.p3d]
path = "p3d"